language: c
os:
  - linux
  - osx
env:
  - ARCH=xen CONF=dbg
  - ARCH=xen CONF=opt
  - ARCH=xen CONF=lto
  - ARCH=posix CONF=dbg
  - ARCH=posix CONF=opt
  - ARCH=posix CONF=lto
before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://s3.amazonaws.com/travis-otp-releases/ubuntu/$(lsb_release -rs)/erlang-17.5-x86_64.tar.bz2; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir ~/otp; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xf erlang-17.5-x86_64.tar.bz2 -C ~/otp/; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source $HOME/otp/17.5/activate; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install erlang; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget http://erlangonxen.org/ElfGCC.dmg.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar xf ElfGCC.dmg.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil mount ElfGCC.dmg; fi
script:
  - PATH=/Volumes/ElfGCC/usr/local/gcc-4.8.1-for-linux64/bin:$PATH make -j2 play ARCH=$ARCH CONF=$CONF
sudo: false
